AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: |
  Deploys ACMAutoValidate Lambda that can be used as a CFN Custom Resources.

  Source: https://github.com/johnbrandborg/aws-acm-autovalidate
  License: Apache 2.0

Parameters:
  pNamePrefix:
    Type: String
    Default: "standalone"
  pOptionalSubdomain:
    Type: String
    Default: ''
  pOptionalDomain:
    Type: String
    Default: ''


Conditions:
  cCreateCert:
    Fn::Not:
    - Fn::And:
      - !Equals [ !Ref pOptionalSubdomain, '' ]
      - !Equals [ !Ref pOptionalDomain, '' ]


Resources:
  rCert:
    Condition: cCreateCert
    Type: Custom::CertificateTest
    Properties:
      ServiceToken: !GetAtt Function.Arn
      domainname: !Join [ '.', [ !Ref pOptionalSubdomain, !Ref pOptionalDomain ] ]
      additionalnames:
        - !Join [ '.', [ "*", !Ref pOptionalSubdomain, !Ref pOptionalDomain ] ]

  Function:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${pNamePrefix}-acm-autovalidate-lambda
      CodeUri: ../../cr/acm_autovalidate
      Handler: index.handler
      Runtime: python3.6
      Timeout: 300
      Policies:
        - Statement:
          - Effect: "Allow"
            Action:
              - "acm:DescribeCertificate"
              - "acm:ListCertificates"
              - "acm:RequestCertificate"
              - "acm:DeleteCertificate"
              - "route53:ListHostedZonesByName"
              - "route53:ChangeResourceRecordSets"
            Resource: "*"

Outputs:
  FunctionArn:
    Value: !GetAtt Function.Arn
#    Export:
#      Name: acm-autovalidate-function-arn