AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  pNamePrefix:
    Type: String
#    Default: 'testnetalpha'
#  pDomain:
#    Type: String
#  pSubdomain:
#    Type: String
  pPublicNodeDomain:
    Type: String
#    Default: 'public-node-0.testnet-alpha.flux.vote.'
  pOffset:
    Type: String
    Default: ''
  pLambdaLayer:
    Type: String


Resources:
  rChaincodeCr:
    Type: Custom::Chaincode
    Properties:
      ServiceToken: !GetAtt rChaincodeLambda.Arn
      pNamePrefix: !Ref pNamePrefix
#      pDomain: !Ref pDomain
#      pSubdomain: !Ref pSubdomain
      pPublicNodeDomain: !Ref pPublicNodeDomain
      pSmartContracts:
        - Name: membership
          Type: deploy
          Output: MembershipAddr
        - Name: membership-add-admin
          Type: calltx
          Function: $membership.addAdmin
          Inputs: [ _members ]
        - Name: bblib-v7
          Type: deploy
        - Libraries:
            __./contracts/BBLib.v7.sol:BBLibV7______: $bblib-v7
            asdf: asdf876
          Name: bbfarm
          Type: deploy
          Output: BBFarmAddr
        - Name: sv-backend
          Type: deploy
          Output: BackendAddr
        - Inputs:
            - ^self
          Name: sv-payments
          Type: deploy
          Output: PaymentsAddr
        - Name: sv-comm-auction
          Type: deploy
        - Inputs:
            - $sv-backend
            - $sv-payments
            - ^addr-ones
            - $bbfarm
            - $sv-comm-auction
          Name: sv-index
          Type: deploy
          Output: IndexAddr
        - Name: ix-backend-perms
          Function: $sv-backend.setPermissions
          Inputs: [ $sv-index, 'bool:true' ]
          Type: calltx
        - Name: ix-payments-perms
          Function: $sv-payments.setPermissions
          Inputs: [ $sv-index, 'bool:true' ]
          Type: calltx
        - Name: ix-bbfarm-perms
          Function: $bbfarm.setPermissions
          Inputs: [ $sv-index, 'bool:true' ]
          Type: calltx
        - Name: ix-mk-democ
          Function: $sv-index.dInit
          Value: 1
          Inputs: [ $membership, 'bool:true' ]
          Type: calltx
          Output: MkDemocTxid
        - Name: democ-hash
          Function: $sv-backend.getGDemoc
          Inputs: [ 'uint256:0' ]
          ReturnTypes: [ 'bytes32' ]
          Type: call
          Output: DemocHash
        - Name: democ-add-admin
          Type: calltx
          Function: $sv-index.setDEditor
          Inputs: [ $democ-hash, _members, 'bool:true' ]


  rChaincodeLambda:
    Type: AWS::Serverless::Function
    Properties:
      Layers: [ !Ref pLambdaLayer ]
      CodeUri: '../cr/chaincode'
      Runtime: python3.6
      Handler: 'chaincode.chaincode_handler'
      FunctionName: !Sub ${pNamePrefix}${pOffset}-chaincode-cr
      Timeout: 300
      Policies:
        - Statement:
          - Effect: Allow
            Action: ssm:GetParameter
            Resource:
              - !Sub "arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/sv-${pNamePrefix}-nodekey-service-publish"
              - !Sub "arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/sv-${pNamePrefix}-param-*"
          - Effect: Allow
            Action:
              - ssm:PutParameter
              - ssm:DeleteParameter
            Resource:
              - !Sub "arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/sv-${pNamePrefix}-param-sc-*"
          - Effect: Allow
            Action:
              - ssm:DescribeParameters
            Resource:
              - '*'
Outputs:
  oMembershipAddr:
    Value: !GetAtt rChaincodeCr.MembershipAddr
  oDemocHash:
    Value: !GetAtt rChaincodeCr.DemocHash
  oMkDemocTxid:
    Value: !GetAtt rChaincodeCr.MkDemocTxid
  oIndexAddr:
    Value: !GetAtt rChaincodeCr.IndexAddr
  oBBFarmAddr:
    Value: !GetAtt rChaincodeCr.BBFarmAddr
