AWSTemplateFormatVersion: '2010-09-09'

Transform:
  - Name: sv-eips
    Parameters:
      pNPublicNodes: !Ref pNPublicNodes

Parameters:
  pNPublicNodes:
    Type: String
  pDependsShim:
    Type: String
    Default: ''
    Description: "This parameter is a shim because DependsOn cannot include functions"


Resources:

  # These will get replaced by the macro and multiplied across our N nodes
  rEip0:
    Type: AWS::EC2::EIP

Outputs:
  oPublicIps:
    Value: !Ref rEip0
  oEipAllocationIds:
    Value: !GetAtt rEip0.AllocationId
  oIgnoreMe:
    Value: !Join [',', [!Ref pDependsShim]]
