AWSTemplateFormatVersion: '2010-09-09'

Transform:
  - Name: sv-eips
    Parameters:
      pNPublicNodes: !Ref pNPublicNodes

Parameters:
  pNPublicNodes:
    Type: String
#  pNamePrefix:
#    Type: String
#  pAvailabilityZone:
#    Type: String
  pDomain:
    Type: String
  pSubdomain:
    Type: String

Resources:

  # These will get replaced by the macro and multiplied across our N nodes
  rEip0:
    Type: AWS::EC2::EIP

  rDomainName0:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneName: !Ref pDomain
      Name: !Sub pnode-0.${pSubdomain}.${pDomain}
      TTL: '60'
      Type: A
      ResourceRecords:
        - !Ref rEip0

Outputs:
  oPublicIps:
    Value: !Ref rEip0
  oEipAllocationIds:
    Value: !GetAtt rEip0.AllocationId
  oDomainNames:
    Value: !Ref rDomainName0