
name: Lint CloudFormation Templates

on: [push]

jobs:
  cloudformation-linter:

    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: cfn-lint
      uses: scottbrenner/cfn-lint-action@master
      with:
        args: stack/**/*.yaml
